### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://aware-queen.surge.sh).

You get a new joke if you refresh the page and click again. It doesn't generate a new joke unless you refresh though. Couldn't figure that out.

**Comment by chrisvfritz** [comment]
I'll adjust the lesson to make it easier. This is good. :shipit:
